### ISSUE TITLE
Sentence Alignment

### ISSUE THREAD

**Issue by lastrucci01** [dsfsi/gov-za-multilingual#8]
#### Description
Use [LASER encodings](https://github.com/facebookresearch/LASER) to perform Sentence alignment on the [govza-cabinet-statements.json](https://github.com/dsfsi/gov-za-multilingual/blob/master/data/govza-cabinet-statements.json) and output in the [data/processed folder](https://github.com/dsfsi/gov-za-multilingual/blob/master/data/processed).

#### Tasks
- [X] Download LASER models
- [X] Data cleanup & sentence tokenisation
- [X] Script to align sentences for 2 languages outputting to a csv 
- [x] (Additional) Script to align sentences for all languages
- [x] Github action to create new aligned csvs on existing [update action](../blob/master/.github/workflows/update_cab_statements.yml) commit
